version: '3.4'

services:
  users_db:
    container_name: users_db_container
    hostname: users_db_host
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
      - MSQL_PID=Express
    restart: always
    networks:
     - user-microservice
    volumes:
     - user_server_data:/var/opt/mssql
    env_file:
     - .env

  sportbetinc:
    container_name: sportbetinc-users-api
    image: ${DOCKER_REGISTRY-}sportbetinc
    build:
      context: .
      dockerfile: SportBetInc/Dockerfile
    ports:
      - 5000:5000
    networks:
      - microservice-network
      - user-microservice
    depends_on:
      - users_db
    restart: always
    env_file:
     - .env

volumes:
  user_server_data: 
  
networks:
  microservice-network:
    external: true
  user-microservice: