version: '3.4'

services:
  users_db:
    user: root
    hostname: users_db
    container_name: users_sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
      - MSQL_PID=Express
    restart: always
    networks:
     - microservice-network
    volumes:
     - sql_server_data:/var/opt/mssql

  sportbetinc:
    container_name: sportbetinc-users-api
    image: ${DOCKER_REGISTRY-}sportbetinc
    build:
      context: .
      dockerfile: SportBetInc/Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - users_db
    networks:
     - microservice-network
    env_file:
     - .env

volumes:
  sql_server_data: 
  
networks:
  microservice-network:
    external: true